Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,32 +1,38 @@
 name: Automatisation des tests
+
 on: push
+
 jobs:
-  Compilation:
+  build-and-test:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Compilation
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up CMake
+        uses: lukka/get-cmake@v3
+
+      - name: Create build directory
+        run: mkdir build
+
+      - name: Run CMake
+        run: cmake -S . -B build
+
+      - name: Build
+        run: cmake --build build
+
+      - name: Run tests
+        run: ctest --test-dir build
+
+      - name: Test function add
         run: |
-          last_directory=$(basename ${{ runner.workspace }})
-          git clone https://github.com/${{ github.repository }}.git
-          cd ./$last_directory
-          mkdir build
           cd build
-          cmake ..
-          make
-          make test
-name: Automatisation des tests2
-on: push
-jobs:
-  Compilation:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Compilation
-        run: |
-          last_directory=$(basename ${{ runner.workspace }})
-          git clone https://github.com/${{ github.repository }}.git
-          cd ./$last_directory
-          mkdir build
-          cd build
-          cmake ..
-          make
-          make test
+          result=$(./src/calculator add 10 5)
+          expected="15.000000"
+          if [ "$result" = "$expected" ]; then
+            echo "Test passed!"
+          else
+            echo "Test failed! Expected $expected but got $result"
+            exit 1
+          fi
